export const projects = [
  {
    title: 'Website for tourism company',
    description: "This is a portfolio website for epic moto tours company. I was given a design and I developed the whole code for the website from scratch. The tech stack we used is HTML, CSS, Javascript. This website includes variety of image coursels and image gallery. I've used best practices for image optimization.",
    image: '/images/9.png',
    tags: ['HTML', 'Css', 'Javascript'],
    visit: 'https://epic-moto.vercel.app/',
    id: 1,
  },
  {
    title: 'Contributed in a startup Ez Age',
    description: "I was one of the early developers in this startup. I got a chance to build, deploy and maintain the project. The tech stack we used is MERN. I was able to handle a tech team. I have implemented user authentications, redux and logics for various UI components. The major part of this product is payment integration, which I did using phonePe.",
    image: '/images/7.png',
    tags: ['MERN', 'Redux', 'System design', 'NodeJs'],
    visit: 'https://ezAge.in',
    id: 2,
  },
  {
    title: 'Portfolio website for a bussiness',
    description: "This is a portfolio website for a bussiness. I was given a design and I developed the whole code for the website from scratch in Next.js 14. I have included animations for hovers, scrolling and smooth scrolling using AOS library. Ive used best practices for SEO using latest Next.js techniques. This protfolio also includes forms and admin panel",
    image: '/images/11.png',
    tags: ['Next.js', 'MongoDB', 'Admin panel', 'Forms'],
    visit: 'https://qubic-gen-portfolio.vercel.app/',
    id: 3,
  },
  {
    title: 'Contributed in a project Memist',
    description: "This is a facebook type application. I was recruited as a part-time developer. I did NodeJs backend development for creating posts, comments and likes etc., and integration with frontend. I also did enable state management using Redux ",
    image: '/images/8.png',
    tags: ['MERN', 'Redux', 'NodeJs', 'System design'],
    visit: 'https://memist.vercel.app/',
    id: 4,
  },
  {
    title: 'Wordpress Site',
    description: "This my first website built as a freelancer. I've used wordpress and its plugins like elementor etc. I've also added custom CSS",
      image: '/images/1.png',
      tags: ['Wordpress', 'CSS', 'HTML', 'PHP'],
    visit: 'https://mahshoplantfella.com',
    id: 0,
  },
  {
    title: 'Full stack login and signup pages',
    description: "As a freelancer I've built login and signup pages which includes otp-signin, gmail login, facebook login, twitter login etc.,",
    image: '/images/4.png',
    tags: ['React', 'NodeJS', 'Mongoose','Postman'],
    visit: 'https://github.com/pmdnawaz1',
    id: 5,
  },
  {
    title: 'WhatsApp Bot',
    description: "This is a WhatsApp bot which takes input from user and inserts data to Google SpreadSheet and also MongoDB collection",
    image: '/images/3.jpg',
    tags: ['NodeJS', 'whatsapp-web.js','google-spreadsheet','mongoose'],
    visit: 'https://github.com/pmdnawaz1/WhatsApptoSheets',
    id: 6,
  },
  {
    title: 'NASA API',
    description:"This API is for an android app of my friend which shows NASA's latest mars photos using NASA mars api. This project helped me to understand how API's work. I've implemented the API in Node JS.",
    image: '/images/2.jpg',
    tags: ['DART', 'FIREBASE'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 7,
  },
  {
    title: 'Telegram bot',
    description: "This is a simple telegram bot deployed in heroku which have telegram group management commands and some fun stuff like generating memes etc.,",
    image: '/images/5.png',
    tags: ['Heroku', 'Python', 'Replit'],
    visit: 'https://github.com/pmdnawaz1/UltroidOppeace',
    id: 9,
  },
  {
    title: 'Flight Management System',
    description: " Allows users to search for available flights, book flights by selecting the desired itinerary, and view their booking details.",
      image: '/images/6.png',
      tags: ['ReactJS', 'NodeJS', 'Express','Jwt'],
    visit: 'https://fms-mern.vercel.app/',
    id: 8,
  },
 
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey towards B.Tech in EEE stream', },
  { year: 2019, text: 'Gained knowledge of Electrical and Electronics stuff out of the box', },
  { year: 2020, text: 'Started Android OS development.', },
  { year: 2021, text: 'Stepped into programming world', },
  { year: 2022, text: 'Started learning web development', },
  { year: 2023, text: 'Started Freelancing and part-time works in web development', },
  { year: 2023, text: 'Joined Loyalytics AI as a full-time developer', },
];